import sqlite3
from pathlib import Path

DB_PATH = Path("primeprop.db")

rows = [
    # March 6
    {
        "timestamp": "2026-03-06T18:00:00+00:00",
        "player_name": "Grayson Allen",
        "stat_type": "Points",
        "market_line": 18.5,
        "projected": 22.1,
        "edge": (22.1 - 18.5) / 18.5,
        "recommended_side": "Over",
        "p_over_model": None,
        "stdev": 8.9,
        "odds": 100.0,
        "over_odds": 100.0,
        "under_odds": -132.0,
        "over_provider": "FanDuel",
        "under_provider": "FanDuel",
    },
    {
        "timestamp": "2026-03-06T18:00:00+00:00",
        "player_name": "P.J. Washington",
        "stat_type": "Points",
        "market_line": 12.5,
        "projected": 14.8,
        "edge": (14.8 - 12.5) / 12.5,
        "recommended_side": "Over",
        "p_over_model": None,
        "stdev": 6.4,
        "odds": -108.0,
        "over_odds": -108.0,
        "under_odds": -115.0,
        "over_provider": "FanDuel",
        "under_provider": "DraftKings",
    },
    {
        "timestamp": "2026-03-06T18:00:00+00:00",
        "player_name": "Bam Adebayo",
        "stat_type": "Points",
        "market_line": 19.5,
        "projected": 21.5,
        "edge": (21.5 - 19.5) / 19.5,
        "recommended_side": "Over",
        "p_over_model": None,
        "stdev": 8.3,
        "odds": 104.0,
        "over_odds": 104.0,
        "under_odds": -126.0,
        "over_provider": "FanDuel",
        "under_provider": "DraftKings",
    },
    {
        "timestamp": "2026-03-06T18:00:00+00:00",
        "player_name": "Nikola Jokic",
        "stat_type": "Rebounds",
        "market_line": 12.5,
        "projected": 13.7,
        "edge": (13.7 - 12.5) / 12.5,
        "recommended_side": "Over",
        "p_over_model": None,
        "stdev": 5.4,
        "odds": 104.0,
        "over_odds": 104.0,
        "under_odds": -138.0,
        "over_provider": "FanDuel",
        "under_provider": "FanDuel",
    },
    {
        "timestamp": "2026-03-06T18:00:00+00:00",
        "player_name": "Kevin Durant",
        "stat_type": "Points",
        "market_line": 26.5,
        "projected": 29.0,
        "edge": (29.0 - 26.5) / 26.5,
        "recommended_side": "Over",
        "p_over_model": None,
        "stdev": 12.2,
        "odds": -102.0,
        "over_odds": -102.0,
        "under_odds": -130.0,
        "over_provider": "FanDuel",
        "under_provider": "FanDuel",
    },
    {
        "timestamp": "2026-03-06T18:00:00+00:00",
        "player_name": "Bam Adebayo",
        "stat_type": "Rebounds",
        "market_line": 9.5,
        "projected": 9.9,
        "edge": (9.9 - 9.5) / 9.5,
        "recommended_side": "Over",
        "p_over_model": None,
        "stdev": 4.1,
        "odds": 110.0,
        "over_odds": 110.0,
        "under_odds": -146.0,
        "over_provider": "FanDuel",
        "under_provider": "FanDuel",
    },
    {
        "timestamp": "2026-03-06T18:00:00+00:00",
        "player_name": "Bam Adebayo",
        "stat_type": "Rebounds",
        "market_line": 8.5,
        "projected": 9.9,
        "edge": (9.9 - 8.5) / 8.5,
        "recommended_side": "Over",
        "p_over_model": None,
        "stdev": 4.1,
        "odds": -138.0,
        "over_odds": -138.0,
        "under_odds": 105.0,
        "over_provider": "DraftKings",
        "under_provider": "DraftKings",
    },
    {
        "timestamp": "2026-03-06T18:00:00+00:00",
        "player_name": "Kawhi Leonard",
        "stat_type": "Points",
        "market_line": 27.5,
        "projected": 29.7,
        "edge": (29.7 - 27.5) / 27.5,
        "recommended_side": "Over",
        "p_over_model": None,
        "stdev": 12.6,
        "odds": -112.0,
        "over_odds": -112.0,
        "under_odds": -118.0,
        "over_provider": "FanDuel",
        "under_provider": "FanDuel",
    },
    {
        "timestamp": "2026-03-06T18:00:00+00:00",
        "player_name": "Jaylen Brown",
        "stat_type": "Points",
        "market_line": 26.5,
        "projected": 25.6,
        "edge": (25.6 - 26.5) / 26.5,
        "recommended_side": "Under",
        "p_over_model": None,
        "stdev": 8.4,
        "odds": -108.0,
        "over_odds": -118.0,
        "under_odds": -108.0,
        "over_provider": "DraftKings",
        "under_provider": "DraftKings",
    },
    {
        "timestamp": "2026-03-06T18:00:00+00:00",
        "player_name": "Jaylen Brown",
        "stat_type": "Points",
        "market_line": 27.5,
        "projected": 25.6,
        "edge": (25.6 - 27.5) / 27.5,
        "recommended_side": "Under",
        "p_over_model": None,
        "stdev": 8.4,
        "odds": -130.0,
        "over_odds": -102.0,
        "under_odds": -130.0,
        "over_provider": "FanDuel",
        "under_provider": "FanDuel",
    },

    # March 7
    {
        "timestamp": "2026-03-07T18:00:00+00:00",
        "player_name": "Tyrese Maxey",
        "stat_type": "Points",
        "market_line": 32.5,
        "projected": 28.6,
        "edge": (28.6 - 32.5) / 32.5,
        "recommended_side": "Under",
        "p_over_model": None,
        "stdev": 11.5,
        "odds": -108.0,
        "over_odds": -118.0,
        "under_odds": -108.0,
        "over_provider": "DraftKings",
        "under_provider": "DraftKings",
    },
    {
        "timestamp": "2026-03-07T18:00:00+00:00",
        "player_name": "Kawhi Leonard",
        "stat_type": "Points",
        "market_line": 26.5,
        "projected": 29.1,
        "edge": (29.1 - 26.5) / 26.5,
        "recommended_side": "Over",
        "p_over_model": None,
        "stdev": 12.8,
        "odds": -104.0,
        "over_odds": -104.0,
        "under_odds": -113.0,
        "over_provider": "FanDuel",
        "under_provider": "DraftKings",
    },
    {
        "timestamp": "2026-03-07T18:00:00+00:00",
        "player_name": "Brandin Podziemski",
        "stat_type": "Points",
        "market_line": 15.5,
        "projected": 17.3,
        "edge": (17.3 - 15.5) / 15.5,
        "recommended_side": "Over",
        "p_over_model": None,
        "stdev": 7.2,
        "odds": -111.0,
        "over_odds": -111.0,
        "under_odds": -105.0,
        "over_provider": "FanDuel",
        "under_provider": "BetMGM",
    },
    {
        "timestamp": "2026-03-07T18:00:00+00:00",
        "player_name": "Tyrese Maxey",
        "stat_type": "Points",
        "market_line": 31.5,
        "projected": 28.6,
        "edge": (28.6 - 31.5) / 31.5,
        "recommended_side": "Under",
        "p_over_model": None,
        "stdev": 11.5,
        "odds": -113.0,
        "over_odds": -105.0,
        "under_odds": -113.0,
        "over_provider": "BetMGM",
        "under_provider": "FanDuel",
    },

    # March 8
    {
        "timestamp": "2026-03-08T18:00:00+00:00",
        "player_name": "Pascal Siakam",
        "stat_type": "Points",
        "market_line": 20.5,
        "projected": 26.9,
        "edge": (26.9 - 20.5) / 20.5,
        "recommended_side": "Over",
        "p_over_model": None,
        "stdev": 10.4,
        "odds": -118.0,
        "over_odds": -118.0,
        "under_odds": -105.0,
        "over_provider": "FanDuel",
        "under_provider": "DraftKings",
    },
    {
        "timestamp": "2026-03-08T18:00:00+00:00",
        "player_name": "Bam Adebayo",
        "stat_type": "Points",
        "market_line": 18.5,
        "projected": 22.4,
        "edge": (22.4 - 18.5) / 18.5,
        "recommended_side": "Over",
        "p_over_model": None,
        "stdev": 8.6,
        "odds": -104.0,
        "over_odds": -104.0,
        "under_odds": -128.0,
        "over_provider": "FanDuel",
        "under_provider": "FanDuel",
    },
    {
        "timestamp": "2026-03-08T18:00:00+00:00",
        "player_name": "Scottie Barnes",
        "stat_type": "Points",
        "market_line": 19.5,
        "projected": 16.3,
        "edge": (16.3 - 19.5) / 19.5,
        "recommended_side": "Under",
        "p_over_model": None,
        "stdev": 7.3,
        "odds": -115.0,
        "over_odds": -111.0,
        "under_odds": -115.0,
        "over_provider": "DraftKings",
        "under_provider": "DraftKings",
    },
    {
        "timestamp": "2026-03-08T18:00:00+00:00",
        "player_name": "Giannis Antetokounmpo",
        "stat_type": "Points",
        "market_line": 25.5,
        "projected": 23.7,
        "edge": (23.7 - 25.5) / 25.5,
        "recommended_side": "Under",
        "p_over_model": None,
        "stdev": 8.8,
        "odds": -102.0,
        "over_odds": -130.0,
        "under_odds": -102.0,
        "over_provider": "FanDuel",
        "under_provider": "FanDuel",
    },
    {
        "timestamp": "2026-03-08T18:00:00+00:00",
        "player_name": "Bam Adebayo",
        "stat_type": "Rebounds",
        "market_line": 9.5,
        "projected": 9.9,
        "edge": (9.9 - 9.5) / 9.5,
        "recommended_side": "Over",
        "p_over_model": None,
        "stdev": 3.9,
        "odds": 110.0,
        "over_odds": 110.0,
        "under_odds": -146.0,
        "over_provider": "FanDuel",
        "under_provider": "FanDuel",
    },
]

conn = sqlite3.connect(DB_PATH)
cur = conn.cursor()

cur.execute("""
CREATE TABLE IF NOT EXISTS picks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TEXT NOT NULL,
    player_name TEXT NOT NULL,
    player_id TEXT,
    nba_player_id INTEGER,
    game_start TEXT,
    stat_type TEXT NOT NULL,
    market_line REAL NOT NULL,
    line REAL,
    projected REAL NOT NULL,
    edge REAL NOT NULL,
    recommended_side TEXT NOT NULL,
    p_over_model REAL,
    stdev REAL,
    odds REAL,
    over_odds REAL,
    under_odds REAL,
    over_provider TEXT,
    under_provider TEXT,
    actual_result REAL,
    won INTEGER
)
""")

for r in rows:
    cur.execute(
        """
        INSERT INTO picks (
            timestamp, player_name, player_id, nba_player_id, game_start,
            stat_type, market_line, line, projected, edge, recommended_side,
            p_over_model, stdev, odds, over_odds, under_odds,
            over_provider, under_provider, actual_result, won
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NULL, NULL)
        """,
        (
            r["timestamp"],
            r["player_name"],
            None,
            None,
            None,
            r["stat_type"],
            r["market_line"],
            r["market_line"],
            r["projected"],
            r["edge"],
            r["recommended_side"],
            r["p_over_model"],
            r["stdev"],
            r["odds"],
            r["over_odds"],
            r["under_odds"],
            r["over_provider"],
            r["under_provider"],
        ),
    )

conn.commit()
conn.close()

print(f"Imported {len(rows)} picks into {DB_PATH}")
